name: CI Pipeline for code quality

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend-checks:
    name: Backend Code Quality & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run Code Linting (Checkstyle)
        run: mvn checkstyle:check -f backend/pom.xml

      - name: Build & Run Tests
        run: mvn clean verify -f backend/pom.xml

      - name: Run Security Scan
        run: mvn dependency-check:check -f backend/pom.xml

  frontend-checks:
    name: Frontend Code Quality & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Run Linter (ESLint)
        run: npx eslint . --ext .js,.jsx
        working-directory: frontend

      - name: Run Tests (Jest)
        run: npm test
        working-directory: frontend

      - name: Check Vulnerabilities
        run: npm audit --audit-level=moderate
        working-directory: frontend

  docker-check:
    name: Dockerfile Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hadolint (Dockerfile Linter)
        run: curl -fsSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint && chmod +x /usr/local/bin/hadolint

      - name: Lint Backend Dockerfile
        run: hadolint backend/Dockerfile

      - name: Lint Frontend Dockerfile
        run: hadolint frontend/DockerFile

      - name: Build Backend Docker Image
        run: docker build -t lostfound-backend backend/

      - name: Build Frontend Docker Image
        run: docker build -t lostfound-frontend frontend/
